C PIXEL DIMENSION FIXED TO 16 BITS
      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*128 IFNAM
        INTEGER W,H
	    PRINT *,'ENTER INPUT BINARY FILENAME'
	    READ (*,*,END=9000,ERR=9100)IFNAM
	    PRINT *,'ENTER WIDTH'
	    READ (*,*,END=9200,ERR=9300) W
	    PRINT *,'ENTER HEIGHT'
	    READ (*,*,END=9400,ERR=9500) H
        CALL M2B(IFNAM,w,H)
        GOTO 9999
9000    PRINT *, 'INPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING INPUT FILE NAME: EXITING' 
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING'
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING'
9999    STOP
      END
C
      
C READ ASCII 8 BITS ARRAY (MATRIX)
C WITH WIDTH COLUMNS AND HEIGHT ROWS
      SUBROUTINE M2B(IFNAM, WIDTH, HEIGHT)
        IMPLICIT NONE
        CHARACTER*128 IFNAM,OFNAM
        INTEGER WIDTH, HEIGHT
        INTEGER MXIDIM,MXJDIM
        INTEGER*2 I16VAL
C Maximum expected dimension
      PARAMETER(MXIDIM=25000,MXJDIM=25000)
C MXIDIM is the maximum dimension on the Y axis (width)
C MXJDIM is the maximum dimension on the X axis (height)
C        INTEGER ROW(MXIDIM)
        CHARACTER*(WIDTH*8) OLINE
        CHARACTER*6 BNUM
        INTEGER CN,CNT,SP
        LOGICAL DEBUG
        INTEGER I,J,POSI
        DEBUG = .FALSE.
        POSI=INDEX(IFNAM,'.')
        OFNAM=IFNAM(1:POSI)//'asc'
        OPEN(11,FILE=IFNAM,FORM='UNFORMATTED',ERR=9500
     &, ACCESS='DIRECT',RECL=2)
        OPEN(12,FILE=OFNAM,ERR=9000)
        CNT=1
        DO 10,J=1,HEIGHT
            DO 20,I=1,WIDTH
                READ(11,REC=CNT,ERR=9100) I16VAL
                IF (DEBUG) PRINT *,' I16VAL ',I16VAL,' I ',I
                WRITE(OLINE((I-1)*7+1:(I-1)*7+7),'(I6,1X)',ERR=9400)
     &I16VAL
                CNT = CNT + 1
20          CONTINUE
            WRITE(OLINE((I-1)*7+8:),'(A2)',ERR=9400) '  '
            DO 50,I=1,LEN(OLINE)
              IF ((OLINE(I:I).LT.CHAR(32))) OLINE(I:I)=CHAR(32)
50          CONTINUE
            WRITE(12,'(A)',ERR=9400) OLINE(1:WIDTH*7+2)
15          IF (DEBUG)  PRINT *,'PROCESSED LINE',J
10      CONTINUE
C END OF ROWS TO PROCESS: GOTO 30
30      CONTINUE
        CLOSE(11)
        CLOSE(12)
        PRINT *,'WROTE ',CNT-1,' WORDS/ELEMENTS'
100     FORMAT(A)
        GOTO 9999
9000    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING THE ROW',J,' REC ',CNT
        GOTO 9999
9400    PRINT *,'ERROR IN WRITING ASCII DATA ON INTERNAL FILE'
        GOTO 9999
9450    PRINT *,'ERROR IN WRITING ASCII ROW'
        GOTO 9999
9500    PRINT *, 'ERROR OPENING INPUT FILE'
9999    STOP
      END
