      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*128 IFNAM
	    PRINT *,'ENTER INPUT BINARY FILENAME'
	    READ (*,*,END=9000,ERR=9100)IFNAM
        CALL M2B(IFNAM)
        GOTO 9999
9000    PRINT *, 'INPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING INPUT FILE NAME: EXITING' 
9999    STOP
      END
C
      
C READ ASCII 8 BITS ARRAY (MATRIX)
C WITH WIDTH COLUMNS AND HEIGHT ROWS
      SUBROUTINE M2B(IFNAM)
        IMPLICIT NONE
        CHARACTER*128 IFNAM,OFNAM
        CHARACTER*1 RBYTE
        INTEGER MXIDIM,MXJDIM,IVAL,I3VAL
C Maximum expected dimension
      PARAMETER(MXIDIM=10,MXJDIM=5)
C MXIDIM is the maximum dimension on the Y axis (width)
C MXJDIM is the maximum dimension on the X axis (height)
C        INTEGER ROW(MXIDIM)
        CHARACTER*(MXIDIM*4) OLINE
        CHARACTER*5 BNUM
        INTEGER CN,CNT,SP
        LOGICAL DEBUG
        INTEGER I,J,POSI
        DEBUG = .FALSE.
        POSI=INDEX(IFNAM,'.')
        OFNAM=IFNAM(1:POSI)//'asc'
        OPEN(11,FILE=IFNAM,FORM='UNFORMATTED',ERR=9500
     &, ACCESS='DIRECT',RECL=1)
        OPEN(12,FILE=OFNAM,ERR=9000)
        CNT=1
        DO 10,J=1,MXJDIM
            DO 20,I=1,MXIDIM
                READ(11,REC=CNT,ERR=9100) RBYTE
                IF (DEBUG) PRINT *,' IVAL ',ICHAR(RBYTE)
                WRITE(OLINE((I-1)*4+1:(I-1)*4+4),'(I3,1X)',ERR=9400)
     &ICHAR(RBYTE)
                CNT = CNT + 1
20          CONTINUE
            WRITE(12,'(A)',ERR=9400) OLINE
15          IF (DEBUG)  PRINT *,'PROCESSED LINE',J
10      CONTINUE
C END OF ROWS TO PROCESS: GOTO 30
30      CONTINUE
        CLOSE(11)
        CLOSE(12)
        PRINT *,'WROTE ',CNT-1,' BYTES/ELEMENTS'
100     FORMAT(A)
        GOTO 9999
9000    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING THE ROW',J,' REC ',CNT
        GOTO 9999
9400    PRINT *,'ERROR IN WRITING ASCII DATA ON INTERNAL FILE'
        GOTO 9999
9450    PRINT *,'ERROR IN WRITING ASCII ROW'
        GOTO 9999
9500    PRINT *, 'ERROR OPENING INPUT FILE'
9999    STOP
      END
