      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*80 OFNAM,IFNAM
        CHARACTER*1 WBYTE
	    INTEGER I,W,H
	    PRINT *,'ENTER INPUT FILENAME'
	    READ *,IFNAM
        CALL RAA(IFNAM)
C	    PRINT *,'ENTER OUTPUT FILENAME'
C	    READ (*,*,END=9000,ERR=9100) OFNAM
C	    PRINT *,'ENTER WIDTH'
C	    READ (*,*,END=9200,ERR=9300) W
C	    PRINT *,'ENTER HEIGHT'
C	    READ (*,*,END=9200,ERR=9300) H
C        CALL WAA(W,H,OFNAM)
	    CALL WBA(W,H,OFNAM)
        GOTO 9999
9000    PRINT *, 'OUTPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING OUTPUT FILE NAME: EXITING' 
        GOTO 9999
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING' 
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING' 
9999    STOP
      END
C
      
C READ ASCII 8 BITS ARRAY (MATRIX)
C WITH WIDTH COLUMNS AND HEIGHT ROWS
      SUBROUTINE RAA(IFNAM)
        IMPLICIT NONE
        CHARACTER*80 IFNAM,OFNAM
        CHARACTER*1 RBYTE
        INTEGER MXIDIM,MXJDIM,IVAL,I3VAL
C Maximum expected dimension
      PARAMETER(MXIDIM=5000,MXJDIM=5000)
C MXIDIM is the maximum dimension on the Y axis (width)
C MXJDIM is the maximum dimension on the X axis (height)
C        INTEGER ROW(MXIDIM)
        CHARACTER*(4*MXIDIM) LINE
        CHARACTER*5 BNUM
        INTEGER CN,CNT,CNT2,SP
        LOGICAL DEBUG
        INTEGER I,J,WIDTH,HEIGHT,POSI
        DEBUG = .FALSE.
        POSI=INDEX(IFNAM,'.')
        OFNAM=IFNAM(1:POSI)//'raw'
        OPEN(11,FILE=IFNAM,ERR=9000)
        OPEN(12,FILE=OFNAM,FORM='UNFORMATTED',ERR=9500
     &, ACCESS='DIRECT',RECL=1)
        BNUM=' '
        CN=1
        CNT=1
        DO 10,J=1,MXJDIM
            SP=0
            LINE=' '
            READ(11,100,ERR=9100,END=30) LINE
            DO 20,I=1,LEN(LINE)
                RBYTE = LINE(I:I)
                IVAL = ICHAR(RBYTE)
                IF (DEBUG) PRINT *,'I:',I,'RBYTE: ',RBYTE,' IVAL ',IVAL
                IF ( (RBYTE.NE.CHAR(32)).AND.(RBYTE.NE.CHAR(10)) ) 
     &          THEN
                  BNUM(CN:CN) = RBYTE
                  CN = CN + 1
                ELSE IF ((CN.GT.1).AND. (RBYTE.EQ.CHAR(32)).AND.
     & (BNUM(CN-1:CN-1).NE.CHAR(32)) ) THEN
                    READ(BNUM, '(I3)', ERR=9300) I3VAL
                    IF (DEBUG) PRINT *,'BNUM:',BNUM,' I3VAL',I3VAL
                    WRITE(12,REC=CNT,ERR=9400) CHAR(I3VAL)
                    CNT = CNT + 1
                    BNUM=' '
                    CN=1
                    SP=0
                ELSE
                    IF (DEBUG) PRINT *,'REST OF THE OPTIONS'
                    IF (SP.GT.4) GOTO 15
                    SP=SP+1
                END IF
20          CONTINUE
15            PRINT *,'PROCESSED LINE',J
10      CONTINUE
C END OF ROWS TO PROCESS: GOTO 30
30      CONTINUE
        CLOSE(11)
        CLOSE(12)
        PRINT *,'WROTE ',CNT-1,' BYTES/ELEMENTS'
100     FORMAT(A)
        GOTO 9999
9000    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING THE ROW',J
        GOTO 9999
9300    PRINT *, 'ERROR CONVERTING NUMBER: ', BNUM
        PRINT *, 'AT POSITION: ', I, J
        GOTO 9999
9400    PRINT *,'ERROR IN WRITING BINARY DATA'
        GOTO 9999
9500    PRINT *, 'ERROR OPENING OUTPUT FILE'
9999    STOP
      END
      CHARACTER*1 FUNCTION GRC(I)
	IMPLICIT NONE
	INTEGER I
	REAL R
	CALL RANDOM_NUMBER(R)
	GRC=CHAR(INT(R*256))
      END

      SUBROUTINE WBA(WIDTH,HEIGHT,OFNAM)
         IMPLICIT NONE
         INTEGER SEED,TIME
         CHARACTER*80 OFNAM
         CHARACTER*1 WBYTE,GRC
	  INTEGER I,WIDTH,HEIGHT
	  SEED=1
	  CALL RANDOM_SEED()
	  OPEN(12,FILE=OFNAM,FORM='UNFORMATTED',ACCESS='DIRECT'
     & ,RECL=1,ERR=9500)
	  DO 10,I=1,WIDTH*HEIGHT
	  WBYTE=GRC(I)
	  WRITE(12,REC=I,ERR=9000) WBYTE
10	  CONTINUE
	  CLOSE(12)
	  GOTO 9999
9000    PRINT *,'ERROR IN WRITING DATA'
	  GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
      
      SUBROUTINE WAA(WIDTH,HEIGHT,OFNAM)
	 IMPLICIT NONE
         INTEGER SEED,TIME
         CHARACTER*80 OFNAM
         CHARACTER*1 WBYTE,GRC
	  INTEGER I,J,WIDTH,HEIGHT
	  SEED=1
	  CALL RANDOM_SEED()
	  OPEN(12,FILE=OFNAM,FORM='FORMATTED',ACCESS='SEQUENTIAL'
     & ,ERR=9500)
      DO 20,J=1,HEIGHT
        DO 10,I=1,WIDTH
	      WBYTE=GRC((J-1)*WIDTH+I)
C	      WRITE(*,'(I4,1X,$)') ICHAR(WBYTE)
	      WRITE(12,100,ERR=9000) ICHAR(WBYTE)
10	    CONTINUE
        WRITE(12,'(A1)',ERR=9000) ' '
C         WRITE(*,'(A1)') CHAR(10)
20    CONTINUE
	  CLOSE(12)
	  GOTO 9999
100   FORMAT(I4,1X,$)
9000    PRINT *,'ERROR IN WRITING DATA'
	  GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
