FC=ftn77
FD=slink
PGPLOT_DIR=C:\pgplot
OEXT=.obj
EEXT=.exe
RM=del /Q /F
FFLAGS=/ANSI
FDFLAGS=
LIBS=$(PGPLOT_DIR)\pgplot.lib
SRCS=pgs.f p1_1.f p2.f rd.f pgs2096x2338.f \
pgs4080x3072.f pgs500x320.f testbyte.f raa.f waa.f wba.f
OBJS = $(SRCS:.f=$(OEXT))
TARGETS = $(OBJS:$(OEXT)=$(EEXT))
.PHONY: all clean

all: $(OBJS) $(TARGETS)

%$(OEXT): %.f
	$(FC) $(FFLAGS) $<

%$(EEXT): %$(OEXT)
	$(FD) $^ -OUT:$@ $(FDFLAGS) $(LIBS)

clean:
	$(RM) $(OBJS) $(TARGETS)


