      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*128 OFNAM
	    INTEGER W,H
	    PRINT *,'ENTER OUTPUT FILENAME'
	    READ (*,*,END=9000,ERR=9100) OFNAM
	    PRINT *,'ENTER WIDTH'
	    READ (*,*,END=9200,ERR=9300) W
	    PRINT *,'ENTER HEIGHT'
	    READ (*,*,END=9400,ERR=9500) H
	    CALL WAA(W,H,OFNAM)
        GOTO 9999
9000    PRINT *, 'OUTPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING OUTPUT FILE NAME: EXITING' 
        GOTO 9999
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING' 
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING' 
9999    STOP
      END
C
      CHARACTER*1 FUNCTION GRC(I)
	    IMPLICIT NONE
	    INTEGER I
	    REAL R
	    CALL RANDOM_NUMBER(R)
	    GRC=CHAR(INT(R*256))
      END
    
      SUBROUTINE WAA(WIDTH,HEIGHT,OFNAM)
 	    IMPLICIT NONE
        CHARACTER*80 OFNAM
        CHARACTER*1 WBYTE,GRC
	    INTEGER I,J,WIDTH,HEIGHT
  	    CALL RANDOM_SEED()
	    OPEN(12,FILE=OFNAM,FORM='FORMATTED',ACCESS='SEQUENTIAL'
     & ,ERR=9500)
        DO 20,J=1,HEIGHT
          DO 10,I=1,WIDTH
	        WBYTE=GRC((J-1)*WIDTH+I)
	        WRITE(12,100,ERR=9000) ICHAR(WBYTE)
10	      CONTINUE
          WRITE(12,'(A1)',ERR=9000) ' '
20      CONTINUE
	    CLOSE(12)
	    GOTO 9999
100     FORMAT(I4,1X,$)
9000    PRINT *,'ERROR IN WRITING ASCII DATA'
	    GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
