      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*80 OFNAM
	    INTEGER W,H
	    PRINT *,'ENTER OUTPUT FILENAME'
	    READ (*,*,END=9000,ERR=9100) OFNAM
	    PRINT *,'ENTER WIDTH'
	    READ (*,*,END=9200,ERR=9300) W
	    PRINT *,'ENTER HEIGHT'
	    READ (*,*,END=9200,ERR=9300) H
	    CALL WAA(W,H,OFNAM)
        GOTO 9999
9000    PRINT *, 'OUTPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING OUTPUT FILE NAME: EXITING' 
        GOTO 9999
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING' 
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING' 
9999    STOP
      END
C
      CHARACTER*1 FUNCTION GRC(I)
	    IMPLICIT NONE
	    INTEGER I
	    REAL R
	    CALL RANDOM_NUMBER(R)
	    GRC=CHAR(INT(R*256))
      END
    
      SUBROUTINE WAA(WIDTH,HEIGHT,OFNAM)
 	    IMPLICIT NONE
        CHARACTER*80 OFNAM
        CHARACTER*1 WBYTE,GRC
	    INTEGER I,J,WIDTH,HEIGHT
  	    CALL RANDOM_SEED()
	    OPEN(12,FILE=OFNAM,FORM='FORMATTED',ACCESS='SEQUENTIAL'
     & ,ERR=9500)
        DO 20,J=1,HEIGHT
          DO 10,I=1,WIDTH
	        WBYTE=GRC((J-1)*WIDTH+I)
	        WRITE(12,100,ERR=9000) ICHAR(WBYTE)
10	      CONTINUE
          WRITE(12,'(A1)',ERR=9000) ' '
20      CONTINUE
	    CLOSE(12)
	    GOTO 9999
100     FORMAT(I4,1X,$)
9000    PRINT *,'ERROR IN WRITING ASCII DATA'
	    GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
C READ ASCII 8 BITS ARRAY (MATRIX)
C WITH WIDTH COLUMNS AND HEIGHT ROWS
      SUBROUTINE RAA(IFNAM)
        IMPLICIT NONE
        CHARACTER*80 IFNAM
        CHARACTER*1 RBYTE
        INTEGER MXIDIM,MXJDIM,IVAL,I3VAL
C Maximum expected dimension
      PARAMETER(MXIDIM=5000,MXJDIM=5000)
C MXIDIM is the maximum dimension on the Y axis (width)
C MXJDIM is the maximum dimension on the X axis (height)
C        INTEGER ROW(MXIDIM)
        CHARACTER*(4*MXIDIM) LINE
        CHARACTER*5 BNUM
        INTEGER CN,CNT,CNT2
        LOGICAL DEBUG
        INTEGER I,J,WIDTH,HEIGHT
        DEBUG = .TRUE.
        OPEN(11,FILE=IFNAM,ERR=9000)
        BNUM=' '
        CN=1
        DO 10,J=1,MXJDIM
            LINE=' '
            READ(11,100,ERR=9100,END=30) LINE
            DO 20,I=1,LEN(LINE)
c             DO 20,I=1,30
                RBYTE = LINE(I:I)
                READ(RBYTE, '(I1)') IVAL
                PRINT *,'I:',I,'RBYTE: ',RBYTE,' IVAL ',IVAL
                IF ( (RBYTE.NE.CHAR(32)).AND.(RBYTE.NE.CHAR(10)) ) 
     &          THEN
                  BNUM(CN:CN) = RBYTE
                  CN = CN + 1
                ELSE IF ((RBYTE.EQ.CHAR(32)).AND.(CN.GT.1)) THEN
                    READ(BNUM, '(I3)', ERR=9300) I3VAL
                    PRINT *,'BNUM:',BNUM,' I3VAL',I3VAL
                    BNUM=' '
                    CN=1
                ELSE
                    PRINT *,'REST OF THE OPTIONS'
                    GOTO 15
                END IF
20          CONTINUE
15            PRINT *,'PROCESSED LINE',J
10      CONTINUE
C END OF ROWS TO PROCESS: GOTO 30
30      CONTINUE
        CLOSE(11)
100     FORMAT(A)
        GOTO 9999
9000    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING THE ROW',J
        GOTO 9999
9300    PRINT *, 'ERROR CONVERTING NUMBER: ', BNUM
        PRINT *, 'AT POSITION: ', I, J
9999    STOP
      END
