      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*80 OFNAM
	    INTEGER W,H
	    PRINT *,'ENTER OUTPUT FILENAME'
	    READ (*,*,END=9000,ERR=9100) OFNAM
	    PRINT *,'ENTER WIDTH'
	    READ (*,*,END=9200,ERR=9300) W
	    PRINT *,'ENTER HEIGHT'
	    READ (*,*,END=9400,ERR=9500) H
	    CALL WAAS(W,H,OFNAM)
        GOTO 9999
9000    PRINT *, 'OUTPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING OUTPUT FILE NAME: EXITING' 
        GOTO 9999
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING' 
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING' 
9999    STOP
      END
C
C ROUTINE TO BE COMPILED WITH THE SALFORD FTN77 COMPILER
      CHARACTER*1 FUNCTION GRCS(I)
 	    IMPLICIT NONE
	    INTEGER I
	    DOUBLE PRECISION R,RANDOM
	    R = RANDOM()
	    GRCS=CHAR(INT(R*256))
      END

      SUBROUTINE WAAS(WIDTH,HEIGHT,OFNAM)
	    IMPLICIT NONE
        CHARACTER*80 OFNAM
        CHARACTER*1 WBYTE,GRCS
	    INTEGER I,J,WIDTH,HEIGHT
        INTEGER MXIDIM
C Maximum expected dimension
        PARAMETER(MXIDIM=5000)
C MXIDIM is the maximum dimension on the Y axis (width)
C        INTEGER ROW(MXIDIM)
        CHARACTER*(4*MXIDIM) LINE
  	    CALL DATE_TIME_SEED@()
	    OPEN(12,FILE=OFNAM,FORM='FORMATTED',ACCESS='SEQUENTIAL'
     & ,ERR=9500)
        DO 20,J=1,HEIGHT
          DO 10,I=1,WIDTH
	        WBYTE=GRCS((J-1)*WIDTH+I)
	        WRITE(LINE(5*(I-1)+1:5*I),100,ERR=9000) ICHAR(WBYTE)
10	      CONTINUE
          WRITE(12,'(A)',ERR=9000) LINE(1:5*WIDTH)
20      CONTINUE
	    CLOSE(12)
	    GOTO 9999
100     FORMAT(I4,1X)
9000    PRINT *,'ERROR IN WRITING DATA ON THE ROW'
	    GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
