      PROGRAM TB
	    IMPLICIT NONE
        CHARACTER*80 OFNAM
	    INTEGER W,H
	    PRINT *,'ENTER OUTPUT FILENAME'
	    READ (*,*,END=9000,ERR=9100) OFNAM
	    PRINT *,'ENTER WIDTH'
	    READ (*,*,END=9200,ERR=9300) W
	    PRINT *,'ENTER HEIGHT'
	    READ (*,*,END=9200,ERR=9300) H
	    CALL WBA(W,H,OFNAM)
        GOTO 9999
9000    PRINT *, 'OUTPUT FILE NAME NOT ENTERED: EXITING'
        GOTO 9999
9100    PRINT *, 'ERROR IN READING OUTPUT FILE NAME: EXITING' 
        GOTO 9999
9200    PRINT *, 'WIDTH NOT ENTERED: EXITING'
        GOTO 9999
9300    PRINT *, 'ERROR IN READING WIDTH: EXITING' 
        GOTO 9999
9400    PRINT *, 'HEIGTH NOT ENTERED: EXITING'
        GOTO 9999
9500    PRINT *, 'ERROR IN READING HEIGHT: EXITING' 
9999    STOP
      END
C
      CHARACTER*1 FUNCTION GRC(I)
	    IMPLICIT NONE
	    INTEGER I
	    REAL R
	    CALL RANDOM_NUMBER(R)
	    GRC=CHAR(INT(R*256))
      END

      SUBROUTINE WBA(WIDTH,HEIGHT,OFNAM)
        IMPLICIT NONE
        CHARACTER*80 OFNAM
        CHARACTER*1 WBYTE,GRC
	    INTEGER I,WIDTH,HEIGHT
	    CALL RANDOM_SEED()
  	    OPEN(12,FILE=OFNAM,FORM='UNFORMATTED',ACCESS='DIRECT'
     & ,RECL=1,ERR=9500)
	    DO 10,I=1,WIDTH*HEIGHT
	      WBYTE=GRC(I)
	      WRITE(12,REC=I,ERR=9000) WBYTE
10	    CONTINUE
	    CLOSE(12)
	    GOTO 9999
9000    PRINT *,'ERROR IN WRITING BINARY DATA'
	    GOTO 9999
9500    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
9999    RETURN
      END
      
